# Generated by Django 3.0.4 on 2020-03-08 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campus',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=250)),
                ('campus_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Campus')),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.CharField(max_length=250)),
                ('counter_part', models.BooleanField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('type_of_fund', models.CharField(max_length=250)),
                ('domain_of_intervation', models.CharField(max_length=250)),
                ('total_cost', models.PositiveIntegerField()),
                ('cost_counter_part', models.PositiveIntegerField()),
                ('currency', models.PositiveSmallIntegerField(choices=[(1, 'RF'), (2, 'USD'), (3, 'EUR')], default=1)),
                ('start_date', models.DateField()),
                ('initial_end_date', models.DateField()),
                ('current_end_date', models.DateField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Campus')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.College')),
                ('project_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'Project info',
                'verbose_name_plural': 'Project info',
            },
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=250)),
                ('output', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('phase', models.PositiveSmallIntegerField(choices=[(1, 'Phase A'), (2, 'Phase B'), (3, 'Phase C'), (4, 'Phase D'), (5, 'Phase E')], default=1)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Ongoing'), (3, 'Closed')], default=1)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'Project Activity',
                'verbose_name_plural': 'Project Activities',
            },
        ),
    ]
